version: '3'
services:

  database:
    image: postgres
    container_name: scrum-poker-database
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
